function handles = guiCHIO(CHIOtab,width,height,left1,left2,prepareCHIO)
% Left panel with a reconstructin parameters CHIO ##################                                                                                                          
        uicontrol('Parent',CHIOtab,'Style','text',...
            'String','CHIO iterations',...
            'Units','normalized','Position',[left1 0.9 width height])      ;        
        handles.hnCHIO = uicontrol('Parent',CHIOtab,'Style','edit',...
            'String',prepareCHIO{1},...
            'Units','normalized','Position',[left2 0.9 width height])      ;
        
        uicontrol('Parent',CHIOtab,'Style','text',...      
            'String','alpha, beta',...                              
            'Units','normalized','Position',[left1 0.83 width height])     ;                                                                                     
        handles.hAlphaCHIO = uicontrol('Parent',CHIOtab,'Style',...     
            'edit','String','0.4',...                                      
            'Units','normalized','Position',[left2 0.83 width/2 height])     ;                                                                                    
        handles.hBetaCHIO = uicontrol('Parent',CHIOtab,'Style',...     
            'edit','String',prepareCHIO{2},...                                      
            'Units','normalized','Position',[left2+width/2 0.83 width/2 height])     ; 
     
        uicontrol('Parent',CHIOtab,'Style','text',...
            'String','Sigma interval',...
            'Units','normalized','Position',[left1 0.76 width height])     ;        
        handles.hSigmaStartCHIO = uicontrol('Parent',CHIOtab,'Style','edit',...
            'String',prepareCHIO{3},...
            'Units','normalized','Position',[left2 0.76 width/2 height])   ;        
        handles.hSigmaEndCHIO = uicontrol('Parent',CHIOtab,'Style','edit',...
            'String',prepareCHIO{4},...
            'Units','normalized','Position',[left2+width/2 0.76 width/2 height]);
        
        uicontrol('Parent',CHIOtab,'Style','text',...
            'String','Srinkwrap interval',...
            'Units','normalized','Position',[left1 0.69 width height])     ;        
        handles.hSrinkwrapStepsCHIO = uicontrol('Parent',CHIOtab,'Style','edit',...
            'String',prepareCHIO{5},...
            'Units','normalized','Position',[left2 0.69 width height])     ;
        
        uicontrol('Parent',CHIOtab,'Style','text',...
            'String','Treshold for Shrinkwrap CHIO',...
            'Units','normalized','Position',[left1 0.62 width height])     ;       
        handles.hTresholdCHIO = uicontrol('Parent',CHIOtab,'Style','edit',...
            'String',prepareCHIO{6},...
            'Units','normalized','Position',[left2 0.62 width height])     ;        
        
        uicontrol('Parent',CHIOtab,'Style','text',...
            'String','Show results step',...
            'Units','normalized','Position',[left1 0.55 width height])     ;       
        handles.hShowStepsCHIO = uicontrol('Parent',CHIOtab,'Style','edit',...
            'String',prepareCHIO{7},...
            'Units','normalized','Position',[left2 0.55 width height])     ;
        
        uicontrol('Parent',CHIOtab,'Style','text',...
            'String','Weight Factor',...
            'Units','normalized','Position',[left1 0.48 width height])     ;       
        handles.hWeightCHIO = uicontrol('Parent',CHIOtab,'Style','edit',...
            'String',prepareCHIO{8},...
            'Units','normalized','Position',[left2 0.48 width height])     ;
        
        uicontrol('Parent',CHIOtab,'Style','text',...
            'String','ViewValue',...
            'Units','normalized','Position',[left1 0.41 width height])     ;       
        handles.hViewValCHIO = uicontrol('Parent',CHIOtab,'Style','edit',...
            'String',prepareCHIO{9},...
            'Units','normalized','Position',[left2 0.41 width height])     ;
        
        uicontrol('Parent',CHIOtab,'Style','text',...
            'String','Error metric',...
            'Units','normalized','Position',[left1 0.34 width height])     ;       
        handles.hErrorMetric = uicontrol('Parent',CHIOtab,'Style','popup',...
            'String',{'reciprocal','real','sharpness'},...
            'Units','normalized','Position',[left2 0.34 width height])     ;
end