function config = guiConfig()
    configF = figure('Name','Config',...
        'NumberTitle','off','units',...
        'normalized','outerposition',[0 0.2 0.4 0.8]);
        set(configF,'ToolBar','none','MenuBar','none');
    
     uicontrol('Parent',leftPanelData,'Style','text',...
    'String','Detector pixel size, [m]',...
    'Units','normalized','Position',[left1 0.4 width height])      ;  
    
    hDetectorPixel = uicontrol('Parent',leftPanelData,'Style','edit',...
            'String','75e-6',...
            'Units','normalized','Position',[left2 0.4 width height])      ;
end

