function handles = guiDM(DMtab,width,height,left1,left2,prepareDM)
% Left panel with a reconstructin parameters DM ###################                                                                                                          
        uicontrol('Parent',DMtab,'Style','text',...
            'String','DM iterations',...
            'Units','normalized','Position',[left1 0.9 width height])      ;        
        handles.hnDM = uicontrol('Parent',DMtab,'Style','edit',...
            'String',prepareDM{1},...
            'Units','normalized','Position',[left2 0.9 width height])      ;
        
        uicontrol('Parent',DMtab,'Style','text',...      
            'String','Feedback parameter',...                              
            'Units','normalized','Position',[left1 0.83 width height])     ;                                                                                     
        handles.hBetaDM = uicontrol('Parent',DMtab,'Style',...     
            'edit','String',prepareDM{2},...                                      
            'Units','normalized','Position',[left2 0.83 width height])     ;         
                
        uicontrol('Parent',DMtab,'Style','text',...
            'String','Sigma interval',...
            'Units','normalized','Position',[left1 0.76 width height])     ;        
        handles.hSigmaStartDM = uicontrol('Parent',DMtab,'Style','edit',...
            'String',prepareDM{3},...
            'Units','normalized','Position',[left2 0.76 width/2 height])   ;        
        handles.hSigmaEndDM = uicontrol('Parent',DMtab,'Style','edit',...
            'String',prepareDM{4},...
            'Units','normalized','Position',[left2+width/2 0.76 width/2 height]);
        
        uicontrol('Parent',DMtab,'Style','text',...
            'String','Srinkwrap interval',...
            'Units','normalized','Position',[left1 0.69 width height])     ;        
        handles.hSrinkwrapStepsDM = uicontrol('Parent',DMtab,'Style','edit',...
            'String',prepareDM{5},...
            'Units','normalized','Position',[left2 0.69 width height])     ;
        
        uicontrol('Parent',DMtab,'Style','text',...
            'String','Treshold for Shrinkwrap DM',...
            'Units','normalized','Position',[left1 0.62 width height])     ;       
        handles.hTresholdDM = uicontrol('Parent',DMtab,'Style','edit',...
            'String',prepareDM{6},...
            'Units','normalized','Position',[left2 0.62 width height])     ;
        
        uicontrol('Parent',DMtab,'Style','text',...
            'String','Show results step',...
            'Units','normalized','Position',[left1 0.55 width height])     ;       
        handles.hShowStepsDM = uicontrol('Parent',DMtab,'Style','edit',...
            'String',prepareDM{7},...
            'Units','normalized','Position',[left2 0.55 width height])     ;
        
        uicontrol('Parent',DMtab,'Style','text',...
            'String','Error metric',...
            'Units','normalized','Position',[left1 0.48 width height])     ;       
        handles.hErrorMetric = uicontrol('Parent',DMtab,'Style','popup',...
            'String',{'reciprocal','real','sharpness'},...
            'Units','normalized','Position',[left2 0.48 width height])     ;
end