function handles = guiER(ERtab,width,height,left1,left2,prepareER)
% Left panel with a reconstructin parameters ER ###################                                                                                                          
        uicontrol('Parent',ERtab,'Style','text',...
            'String','ER iterations',...
            'Units','normalized','Position',[left1 0.9 width height])      ;        
        handles.hnER = uicontrol('Parent',ERtab,'Style','edit',...
            'String',prepareER{1},...
            'Units','normalized','Position',[left2 0.9 width height])      ;
        
        uicontrol('Parent',ERtab,'Style','text',...      
            'String','Feedback parameter',...                              
            'Units','normalized','Position',[left1 0.83 width height])     ;                                                                                     
        handles.hBetaER = uicontrol('Parent',ERtab,'Style',...     
            'edit','String',prepareER{2},...                                      
            'Units','normalized','Position',[left2 0.83 width height])     ;         
                
        uicontrol('Parent',ERtab,'Style','text',...
            'String','Sigma interval',...
            'Units','normalized','Position',[left1 0.76 width height])     ;        
        handles.hSigmaStartER = uicontrol('Parent',ERtab,'Style','edit',...
            'String',prepareER{3},...
            'Units','normalized','Position',[left2 0.76 width/2 height])   ;        
        handles.hSigmaEndER = uicontrol('Parent',ERtab,'Style','edit',...
            'String',prepareER{4},...
            'Units','normalized','Position',[left2+width/2 0.76 width/2 height]);
        
        uicontrol('Parent',ERtab,'Style','text',...
            'String','Srinkwrap interval',...
            'Units','normalized','Position',[left1 0.69 width height])     ;        
        handles.hSrinkwrapStepsER = uicontrol('Parent',ERtab,'Style','edit',...
            'String',prepareER{5},...
            'Units','normalized','Position',[left2 0.69 width height])     ;
        
        uicontrol('Parent',ERtab,'Style','text',...
            'String','Treshold for Shrinkwrap ER',...
            'Units','normalized','Position',[left1 0.62 width height])     ;       
        handles.hTresholdER = uicontrol('Parent',ERtab,'Style','edit',...
            'String',prepareER{6},...
            'Units','normalized','Position',[left2 0.62 width height])     ;
        
        uicontrol('Parent',ERtab,'Style','text',...
            'String','Show results step',...
            'Units','normalized','Position',[left1 0.55 width height])     ;       
        handles.hShowStepsER = uicontrol('Parent',ERtab,'Style','edit',...
            'String',prepareER{7},...
            'Units','normalized','Position',[left2 0.55 width height])     ;
        
        uicontrol('Parent',ERtab,'Style','text',...
            'String','Error metric',...
            'Units','normalized','Position',[left1 0.48 width height])     ;       
        handles.hErrorMetric = uicontrol('Parent',ERtab,'Style','popup',...
            'String',{'reciprocal','real','sharpness'},...
            'Units','normalized','Position',[left2 0.48 width height])     ;                
        
end