function handles = guiGA(GAtab,width,height,left1,left2,algorithmCombinations)         
    uicontrol('Parent',GAtab,'Style','text',...
            'String','Iterations',...
            'Units','normalized','Position',[0.05 0.9 0.25 height])      ;      
    uicontrol('Parent',GAtab,'Style','text',...
            'String','Population',...
            'Units','normalized','Position',[0.35 0.9 0.25 height])      ; 
    uicontrol('Parent',GAtab,'Style','text',...
            'String','Generations',...
            'Units','normalized','Position',[0.65 0.9 0.27 height])      ; 
        
        handles.hnIterationsGA = uicontrol('Parent',GAtab,'Style','edit',...
            'String','3',...
            'Units','normalized','Position',[0.05 0.84 0.25 height])      ;        
        handles.hnPopulationGA = uicontrol('Parent',GAtab,'Style','edit',...
            'String','5',...
            'Units','normalized','Position',[0.35 0.84 0.25 height])      ;        
        handles.hnGenerationsGA = uicontrol('Parent',GAtab,'Style','edit',...
            'String','5',...
            'Units','normalized','Position',[0.65 0.84 0.25 height])      ;                                       
        
        uicontrol('Parent',GAtab,'Style','text',...
            'String','SW',...
            'Units','normalized','Position',[0.05 0.69 0.25 height])     ;        
        handles.hShrinkWrapGA = uicontrol('Parent',GAtab,'Style','checkbox',...
            'Value',1,...
            'Units','normalized','Position',[0.35 0.69 0.25/3 height])     ;                
            
        uicontrol('Parent',GAtab,'Style','text',...
            'String','Sigma',...
            'Units','normalized','Position',[0.45 0.69 0.25/1.5 height])     ;
        
            handles.hSigmaStartGA = uicontrol('Parent',GAtab,'Style','edit',...
                'String','5',...
                'Units','normalized','Position',[0.61 0.69 0.25/2 height])   ; 
             
            handles.hSigmaEndGA = uicontrol('Parent',GAtab,'Style','edit',...
                'String','1',...
                'Units','normalized','Position',[0.775 0.69 0.25/2 height]);                     
        
        uicontrol('Parent',GAtab,'Style','text',...
            'String','Srinkwrap interval',...
            'Units','normalized','Position',[0.05 0.62 0.25 height])     ;        
        handles.hSrinkwrapStepsGA = uicontrol('Parent',GAtab,'Style','edit',...
            'String',10,...
            'Units','normalized','Position',[0.35 0.62 0.25 height])     ;

        uicontrol('Parent',GAtab,'Style','text',...
            'String','Treshold for Shrinkwrap',...
            'Units','normalized','Position',[0.05 0.55 0.25 height])     ;       
        handles.hTresholdGA = uicontrol('Parent',GAtab,'Style','edit',...
            'String',0.2,...
            'Units','normalized','Position',[0.35 0.55 0.25 height])     ;  
            
        uicontrol('Parent',GAtab,'Style','text',...
            'String','Low-res to High-res',...
            'Units','normalized','Position',[0.05 0.48 0.25 height])     ;        
        handles.hLowHighResGA = uicontrol('Parent',GAtab,'Style','checkbox',...
            'Value',0,...
            'Units','normalized','Position',[0.35 0.48 0.25/3 height])     ;   
        
        uicontrol('Parent',GAtab,'Style','text',...
            'String','Omega',...
            'Units','normalized','Position',[0.45 0.48 0.25/1.5 height])     ;
        
            handles.hOmegaStartGA = uicontrol('Parent',GAtab,'Style','edit',...
                'String','0.1',...
                'Units','normalized','Position',[0.61 0.48 0.25/2 height])   ; 
             
            handles.hOmegaEndGA = uicontrol('Parent',GAtab,'Style','edit',...
                'String','1',...
                'Units','normalized','Position',[0.775 0.48 0.25/2 height]);  
       
        uicontrol('Parent',GAtab,'Style','text',...
            'String','Partial coherence',...
            'Units','normalized','Position',[0.05 0.41 0.25 height])     ;        
        handles.hPartialCoherenceGA = uicontrol('Parent',GAtab,'Style','checkbox',...
            'Value',0,...
            'Units','normalized','Position',[0.35 0.41 0.25/3 height])     ;
        
        uicontrol('Parent',GAtab,'Style','text',...
            'String','Error metric',...
            'Units','normalized','Position',[left1 0.34 width height])     ;       
        handles.hErrorMetric = uicontrol('Parent',GAtab,'Style','popup',...
            'String',{'reciprocal','real','sharpness'},...
            'Units','normalized','Position',[left2 0.34 width height])     ;

end