function handles = guiHIO(HIOtab,width,height,left1,left2,prepareHIO)
% Left panel with a reconstructin parameters HIO ##################                                                                                                          
        uicontrol('Parent',HIOtab,'Style','text',...
            'String','HIO iterations',...
            'Units','normalized','Position',[left1 0.9 width height])      ;        
        handles.hnHIO = uicontrol('Parent',HIOtab,'Style','edit',...
            'String',prepareHIO{1},...
            'Units','normalized','Position',[left2 0.9 width height])      ;
        
        uicontrol('Parent',HIOtab,'Style','text',...      
            'String','Feedback parameter',...                              
            'Units','normalized','Position',[left1 0.83 width height])     ;                                                                                     
        handles.hBetaHIO = uicontrol('Parent',HIOtab,'Style',...     
            'edit','String',prepareHIO{2},...                                      
            'Units','normalized','Position',[left2 0.83 width height])     ;         
                
        uicontrol('Parent',HIOtab,'Style','text',...
            'String','Sigma interval',...
            'Units','normalized','Position',[left1 0.76 width height])     ;        
        handles.hSigmaStartHIO = uicontrol('Parent',HIOtab,'Style','edit',...
            'String',prepareHIO{3},...
            'Units','normalized','Position',[left2 0.76 width/2 height])   ;        
        handles.hSigmaEndHIO = uicontrol('Parent',HIOtab,'Style','edit',...
            'String',prepareHIO{4},...
            'Units','normalized','Position',[left2+width/2 0.76 width/2 height]);
        
        uicontrol('Parent',HIOtab,'Style','text',...
            'String','Srinkwrap interval',...
            'Units','normalized','Position',[left1 0.69 width height])     ;        
        handles.hSrinkwrapStepsHIO = uicontrol('Parent',HIOtab,'Style','edit',...
            'String',prepareHIO{5},...
            'Units','normalized','Position',[left2 0.69 width height])     ;
        
        uicontrol('Parent',HIOtab,'Style','text',...
            'String','Treshold for Shrinkwrap HIO',...
            'Units','normalized','Position',[left1 0.62 width height])     ;       
        handles.hTresholdHIO = uicontrol('Parent',HIOtab,'Style','edit',...
            'String',prepareHIO{6},...
            'Units','normalized','Position',[left2 0.62 width height])     ;        
        
        uicontrol('Parent',HIOtab,'Style','text',...
            'String','Show results step',...
            'Units','normalized','Position',[left1 0.55 width height])     ;       
        handles.hShowStepsHIO = uicontrol('Parent',HIOtab,'Style','edit',...
            'String',prepareHIO{7},...
            'Units','normalized','Position',[left2 0.55 width height])     ;
        
        uicontrol('Parent',HIOtab,'Style','text',...
            'String','Error metric',...
            'Units','normalized','Position',[left1 0.48 width height])     ;       
        handles.hErrorMetric = uicontrol('Parent',HIOtab,'Style','popup',...
            'String',{'reciprocal','real','sharpness'},...
            'Units','normalized','Position',[left2 0.48 width height])     ;
end