function handles = guiRAAR(RAARtab,width,height,left1,left2,prepareRAAR)
% Left panel with a reconstructin parameters RAAR #################                                                                                                          
        uicontrol('Parent',RAARtab,'Style','text',...
            'String','RAAR iterations',...
            'Units','normalized','Position',[left1 0.9 width height])      ;        
        handles.hnRAAR = uicontrol('Parent',RAARtab,'Style','edit',...
            'String',prepareRAAR{1},...
            'Units','normalized','Position',[left2 0.9 width height])      ;
        
        uicontrol('Parent',RAARtab,'Style','text',...      
            'String','Feedback parameter',...                              
            'Units','normalized','Position',[left1 0.83 width height])     ;                                                                                     
        handles.hBetaRAAR = uicontrol('Parent',RAARtab,'Style',...     
            'edit','String',prepareRAAR{2},...                                      
            'Units','normalized','Position',[left2 0.83 width height])     ;         
                
        uicontrol('Parent',RAARtab,'Style','text',...
            'String','Sigma interval',...
            'Units','normalized','Position',[left1 0.76 width height])     ;        
        handles.hSigmaStartRAAR = uicontrol('Parent',RAARtab,'Style','edit',...
            'String',prepareRAAR{3},...
            'Units','normalized','Position',[left2 0.76 width/2 height])   ;        
        handles.hSigmaEndRAAR = uicontrol('Parent',RAARtab,'Style','edit',...
            'String',prepareRAAR{4},...
            'Units','normalized','Position',[left2+width/2 0.76 width/2 height]);
        
        uicontrol('Parent',RAARtab,'Style','text',...
            'String','Srinkwrap interval',...
            'Units','normalized','Position',[left1 0.69 width height])     ;        
        handles.hSrinkwrapStepsRAAR = uicontrol('Parent',RAARtab,'Style','edit',...
            'String',prepareRAAR{5},...
            'Units','normalized','Position',[left2 0.69 width height])     ;
        
        uicontrol('Parent',RAARtab,'Style','text',...
            'String','Treshold for Shrinkwrap RAAR',...
            'Units','normalized','Position',[left1 0.62 width height])     ;       
        handles.hTresholdRAAR = uicontrol('Parent',RAARtab,'Style','edit',...
            'String',prepareRAAR{6},...
            'Units','normalized','Position',[left2 0.62 width height])     ;
        
        uicontrol('Parent',RAARtab,'Style','text',...
            'String','Show results step',...
            'Units','normalized','Position',[left1 0.55 width height])     ;       
        handles.hShowStepsRAAR = uicontrol('Parent',RAARtab,'Style','edit',...
            'String',prepareRAAR{7},...
            'Units','normalized','Position',[left2 0.55 width height])     ;
        
        uicontrol('Parent',RAARtab,'Style','text',...
            'String','Error metric',...
            'Units','normalized','Position',[left1 0.48 width height])     ;       
        handles.hErrorMetric = uicontrol('Parent',RAARtab,'Style','popup',...
            'String',{'reciprocal','real','sharpness'},...
            'Units','normalized','Position',[left2 0.48 width height])     ;
end