function handles = guiSF(SFtab,width,height,left1,left2,prepareSF)
% Left panel with a reconstructin parameters SF ###################                                                                                                          
        uicontrol('Parent',SFtab,'Style','text',...
            'String','SF iterations',...
            'Units','normalized','Position',[left1 0.9 width height])      ;        
        handles.hnSF = uicontrol('Parent',SFtab,'Style','edit',...
            'String',prepareSF{1},...
            'Units','normalized','Position',[left2 0.9 width height])      ;
        
        uicontrol('Parent',SFtab,'Style','text',...      
            'String','Feedback parameter',...                              
            'Units','normalized','Position',[left1 0.83 width height])     ;                                                                                     
        handles.hBetaSF = uicontrol('Parent',SFtab,'Style',...     
            'edit','String',prepareSF{2},...                                      
            'Units','normalized','Position',[left2 0.83 width height])     ;         
                
        uicontrol('Parent',SFtab,'Style','text',...
            'String','Sigma interval',...
            'Units','normalized','Position',[left1 0.76 width height])     ;        
        handles.hSigmaStartSF = uicontrol('Parent',SFtab,'Style','edit',...
            'String',prepareSF{3},...
            'Units','normalized','Position',[left2 0.76 width/2 height])   ;        
        handles.hSigmaEndSF = uicontrol('Parent',SFtab,'Style','edit',...
            'String',prepareSF{4},...
            'Units','normalized','Position',[left2+width/2 0.76 width/2 height]);
        
        uicontrol('Parent',SFtab,'Style','text',...
            'String','Srinkwrap interval',...
            'Units','normalized','Position',[left1 0.69 width height])     ;        
        handles.hSrinkwrapStepsSF = uicontrol('Parent',SFtab,'Style','edit',...
            'String',prepareSF{5},...
            'Units','normalized','Position',[left2 0.69 width height])     ;
        
        uicontrol('Parent',SFtab,'Style','text',...
            'String','Treshold for Shrinkwrap SF',...
            'Units','normalized','Position',[left1 0.62 width height])     ;       
        handles.hTresholdSF = uicontrol('Parent',SFtab,'Style','edit',...
            'String',prepareSF{6},...
            'Units','normalized','Position',[left2 0.62 width height])     ;
        
        uicontrol('Parent',SFtab,'Style','text',...
            'String','Show results step',...
            'Units','normalized','Position',[left1 0.55 width height])     ;       
        handles.hShowStepsSF = uicontrol('Parent',SFtab,'Style','edit',...
            'String',prepareSF{7},...
            'Units','normalized','Position',[left2 0.55 width height])     ;
        
        uicontrol('Parent',SFtab,'Style','text',...
            'String','Error metric',...
            'Units','normalized','Position',[left1 0.48 width height])     ;       
        handles.hErrorMetric = uicontrol('Parent',SFtab,'Style','popup',...
            'String',{'reciprocal','real','sharpness'},...
            'Units','normalized','Position',[left2 0.48 width height])     ;
end