function handles = guiModTools(ModTab,width,height,left1,left2,prepareASR)
% Left panel with a reconstructin parameters ASR ##################                                                                                                          
        uicontrol('Parent',ModTab,'Style','text',...
            'String','ASR iterations',...
            'Units','normalized','Position',[left1 0.9 width height])      ;        
        handles.hnASR = uicontrol('Parent',ModTab,'Style','edit',...
            'String',prepareASR{1},...
            'Units','normalized','Position',[left2 0.9 width height])      ;
        
        uicontrol('Parent',ModTab,'Style','text',...      
            'String','Feedback parameter',...                              
            'Units','normalized','Position',[left1 0.83 width height])     ;                                                                                     
        handles.hBetaASR = uicontrol('Parent',ModTab,'Style',...     
            'edit','String',prepareASR{2},...                                      
            'Units','normalized','Position',[left2 0.83 width height])     ;         
                
        uicontrol('Parent',ModTab,'Style','text',...
            'String','Sigma interval',...
            'Units','normalized','Position',[left1 0.76 width height])     ;        
        handles.hSigmaStartASR = uicontrol('Parent',ModTab,'Style','edit',...
            'String',prepareASR{3},...
            'Units','normalized','Position',[left2 0.76 width/2 height])   ;        
        handles.hSigmaEndASR = uicontrol('Parent',ModTab,'Style','edit',...
            'String',prepareASR{4},...
            'Units','normalized','Position',[left2+width/2 0.76 width/2 height]);
        
        uicontrol('Parent',ModTab,'Style','text',...
            'String','Srinkwrap interval',...
            'Units','normalized','Position',[left1 0.69 width height])     ;        
        handles.hSrinkwrapStepsASR = uicontrol('Parent',ModTab,'Style','edit',...
            'String',prepareASR{5},...
            'Units','normalized','Position',[left2 0.69 width height])     ;
        
        uicontrol('Parent',ModTab,'Style','text',...
            'String','Treshold for Shrinkwrap ASR',...
            'Units','normalized','Position',[left1 0.62 width height])     ;       
        handles.hTresholdASR = uicontrol('Parent',ModTab,'Style','edit',...
            'String',prepareASR{6},...
            'Units','normalized','Position',[left2 0.62 width height])     ;
        
        uicontrol('Parent',ModTab,'Style','text',...
            'String','Show results step',...
            'Units','normalized','Position',[left1 0.55 width height])     ;       
        handles.hShowStepsASR = uicontrol('Parent',ModTab,'Style','edit',...
            'String',prepareASR{7},...
            'Units','normalized','Position',[left2 0.55 width height])     ;
        
        uicontrol('Parent',ModTab,'Style','text',...
            'String','Error metric',...
            'Units','normalized','Position',[left1 0.48 width height])     ;       
        handles.hErrorMetric = uicontrol('Parent',ModTab,'Style','popup',...
            'String',{'reciprocal','real','sharpness'},...
            'Units','normalized','Position',[left2 0.48 width height])     ;
end